import type { FormData } from "./inspecaoMedica.types";
export const createFormData = (): FormData => ({
  nome: "",
  endereco: "",
  numeroCasa: "",
  data: "",
  funcao: "",
  matricula: "",
  lotacao: "",
  emailServidor: "",
  admissao: "",
  sexo: "",
  estadoCivil: "",
  regime: "",
  cpf: "",
  cargo: "",
  // localTrabalho: "",
  ramal: "",
  bairro: "",
  complemento: "",
  dataSaida: "",
  dataRetorno: "",
  dataAssinaturaServidor: "",
  dataAssinaturaChefe: "",
  descricaoFuncoes: "",
  funcaoConfianca: "nao",
  funcaoGESAT: "Outros",
  funcaoAfastamento: "Sim",
  afastadoReadaptado: "Sim",
  nomePaciente: "",
  dataAfastamentoReadaptado: "",
  afastadoConsecutivamente: "Não",
  dataAfastamento: "",
  outrosFuncaoGESAT: "",
  anamnese: "",
  exames: "",
  diagnostico: "",
  cid: "",
  contato: "",
});
