import type { FormData } from "./solicitacaoCursos.types";
export const createFormData = (): FormData => ({
  nome: "",
  endereco: "",
  celular: "",
  identidade: "",
  matricula: "",
  lotacao: "",
  emailServidor: "",
  cpf: "",
  cargo: "",
  ramal: "",
  funcaoConfianca: "nao",
  tipoFuncao: "nenhum",
  qualFuncao: "",
  descricaoCurso: "",
  fornecedor: "",
  cnpj: "",
  contato: "",
  whatsapp: "",
  emailFornecedor: "",
  periodoRealizacao: "",
  inicioTermino: "",
  cargaHorariaTotal: "",
  cargaHorariaDiaria: "",
  usoProgressao: "nao",
  formaApresentacao: "",
  solicitaInscricao: "nao",
  valorInscricao: "",
  solicitaMensalidade: "nao",
  valorMensalidade: "",
  valorTotal: "",
});
